(() => {
  const DATA = window.CARE_MANAGEMENT_DATA;
  const charts = {};
  const state = { page:'patients', patientPage:1, intakePage:1, callPage:1, patientSize:100, intakeSize:50, callSize:75 };
  const COLORS = ['#7da9d8','#e5ad6f','#7fb497','#76b4bd','#c69aae','#d98a8a','#9db9d5','#edc18f','#89b8a2','#b7a1c3'];

  const $ = id => document.getElementById(id);
  const str = v => String(v ?? '').trim();
  const lower = v => str(v).toLowerCase();
  const esc = v => str(v).replace(/[&<>'"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  const pct = (a,b) => b ? `${(a/b*100).toFixed(1)}%` : '0.0%';
  const num = v => Number(v || 0).toLocaleString();
  const uniq = arr => [...new Set(arr.filter(v => str(v)))].sort((a,b)=>String(a).localeCompare(String(b)));
  const countBy = (arr, fn) => arr.reduce((o,x)=>{const k=str(fn(x))||'Unknown';o[k]=(o[k]||0)+1;return o;},{});
  const sortedEntries = obj => Object.entries(obj).sort((a,b)=>b[1]-a[1]);
  const isConnected = c => ['connected','answered'].includes(lower(c.response));
  const hasOutreach = p => Boolean(str(p.status)||str(p.attempt1Date)||str(p.attempt2Date)||str(p.attempt3Date));
  const hasReached = p => [p.attempt1Outcome,p.attempt2Outcome,p.attempt3Outcome].some(v => lower(v).includes('reached'));

  function fmtDate(v){ if(!v) return '—'; const s=str(v); const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/); return m ? `${m[2]}/${m[3]}/${m[1]}` : s; }
  function fmtDateTime(v){ if(!v) return '—'; const d=new Date(v); return Number.isNaN(d.getTime()) ? str(v) : d.toLocaleString(); }
  function fmtDuration(sec){ sec=Number(sec||0); const m=Math.floor(sec/60), s=Math.round(sec%60); return m ? `${m}m ${s}s` : `${s}s`; }
  function kpi(icon,label,value,sub,color){ return `<article class="kpi-card" style="--card-color:${color}"><div class="kpi-icon">${icon}</div><div class="kpi-label">${esc(label)}</div><div class="kpi-value">${esc(value)}</div><div class="kpi-sub">${esc(sub)}</div></article>`; }
  function badge(text,kind='muted'){ return `<span class="badge badge-${kind}">${esc(text||'—')}</span>`; }
  function statusBadge(v){ const s=lower(v); if(!s)return badge('Not Started','muted'); if(s.includes('enrolled')||s==='assessment completed'||s==='reached')return badge(v,'teal'); if(s==='in progress')return badge(v,'blue'); if(s==='closed')return badge(v,'purple'); if(s.includes('unable')||s.includes('declined')||s.includes('not a good'))return badge(v,'red'); return badge(v,'amber'); }
  function priorityBadge(v){ const s=lower(v); if(s==='high')return badge(v,'red'); if(s==='moderate')return badge(v,'amber'); if(s==='low')return badge(v,'teal'); return badge('—','muted'); }
  function formBadge(v){ return lower(v)==='received' ? badge('Received','teal') : lower(v).includes('not received') ? badge(v,'red') : badge(v||'Outstanding','amber'); }
  function responseBadge(v){ const s=lower(v); if(s==='connected'||s==='answered')return badge(v,'teal'); if(s.includes('not'))return badge(v,'red'); return badge(v,'amber'); }

  function destroyChart(key){ if(charts[key]){charts[key].destroy(); delete charts[key];} }
  function baseChartOptions(extra={}){ return {responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#60758a',boxWidth:12}},tooltip:{backgroundColor:'#ffffff',titleColor:'#2f485f',bodyColor:'#465b70',borderColor:'#d8e2ec',borderWidth:1}},scales:{x:{ticks:{color:'#718096'},grid:{color:'rgba(160,178,196,.22)'}},y:{ticks:{color:'#718096'},grid:{color:'rgba(160,178,196,.22)'},beginAtZero:true}},...extra}; }
  function makeChart(key,id,type,labels,datasets,options={}){ destroyChart(key); const canvas=$(id); if(!canvas || !window.Chart) return; charts[key]=new Chart(canvas,{type,data:{labels,datasets},options:baseChartOptions(options)}); }
  function makeDoughnut(key,id,labels,data){ destroyChart(key); const canvas=$(id); if(!canvas || !window.Chart)return; charts[key]=new Chart(canvas,{type:'doughnut',data:{labels,datasets:[{data,backgroundColor:labels.map((_,i)=>COLORS[i%COLORS.length]),borderColor:'#ffffff',borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,cutout:'63%',plugins:{legend:{position:'bottom',labels:{color:'#60758a',boxWidth:12}},tooltip:{backgroundColor:'#ffffff',titleColor:'#2f485f',bodyColor:'#465b70',borderColor:'#d8e2ec',borderWidth:1}}}}); }

  function fillSelect(id, values, firstLabel){ const el=$(id); el.innerHTML=`<option value="All">${esc(firstLabel)}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join(''); }
  function showApp(){ $('loadingScreen').classList.add('hidden'); $('mainHeader').classList.remove('hidden'); $('pageNav').classList.remove('hidden'); $('mainContent').classList.remove('hidden'); }
  function showError(){ $('loadingScreen').classList.add('hidden'); $('errorScreen').classList.remove('hidden'); }

  function init(){
    if(!DATA || !Array.isArray(DATA.patients) || !Array.isArray(DATA.intakeForms) || !Array.isArray(DATA.calls)){ showError(); return; }
    $('lastUpdated').textContent=`Updated ${new Date(DATA.lastUpdated).toLocaleString()}`;
    fillSelect('patientAcoFilter',uniq(DATA.patients.map(x=>x.aco)),'All ACOs');
    fillSelect('patientNurseFilter',['Unassigned',...uniq(DATA.patients.map(x=>x.nurse))],'All Nurses');
    fillSelect('patientPriorityFilter',['No Priority',...uniq(DATA.patients.map(x=>x.priority))],'All Priorities');
    fillSelect('patientStatusFilter',['Not Started',...uniq(DATA.patients.map(x=>x.status))],'All Statuses');
    fillSelect('intakeAcoFilter',uniq(DATA.intakeForms.map(x=>x.aco)),'All ACOs');
    fillSelect('intakeConsultantFilter',uniq(DATA.intakeForms.map(x=>x.consultant)),'All Consultants');
    fillSelect('intakeStateFilter',uniq(DATA.intakeForms.map(x=>x.formState)),'All Form Statuses');
    fillSelect('callStaffFilter',uniq(DATA.calls.map(x=>x.owner).filter(x=>x!=='Unassigned')),'All Staff');
    fillSelect('callDirectionFilter',uniq(DATA.calls.map(x=>x.direction)),'All Directions');
    fillSelect('callResponseFilter',uniq(DATA.calls.map(x=>x.response)),'All Responses');
    registerEvents(); showApp(); renderPatients();
  }

  function registerEvents(){
    document.querySelectorAll('.page-button').forEach(btn=>btn.addEventListener('click',()=>switchPage(btn.dataset.page)));
    let pt; $('patientSearch').addEventListener('input',()=>{clearTimeout(pt);pt=setTimeout(()=>{state.patientPage=1;renderPatients();},220)});
    ['patientAcoFilter','patientNurseFilter','patientPriorityFilter','patientStatusFilter'].forEach(id=>$(id).addEventListener('change',()=>{state.patientPage=1;renderPatients();}));
    $('patientClear').addEventListener('click',()=>{ $('patientSearch').value=''; ['patientAcoFilter','patientNurseFilter','patientPriorityFilter','patientStatusFilter'].forEach(id=>$(id).value='All'); state.patientPage=1; renderPatients(); });
    $('patientPrev').addEventListener('click',()=>{if(state.patientPage>1){state.patientPage--;renderPatientTable(getFilteredPatients());}}); $('patientNext').addEventListener('click',()=>{state.patientPage++;renderPatientTable(getFilteredPatients());});

    let it; $('intakeSearch').addEventListener('input',()=>{clearTimeout(it);it=setTimeout(()=>{state.intakePage=1;renderIntake();},220)});
    ['intakeAcoFilter','intakeConsultantFilter','intakeStateFilter'].forEach(id=>$(id).addEventListener('change',()=>{state.intakePage=1;renderIntake();}));
    $('intakeClear').addEventListener('click',()=>{ $('intakeSearch').value=''; ['intakeAcoFilter','intakeConsultantFilter','intakeStateFilter'].forEach(id=>$(id).value='All'); state.intakePage=1; renderIntake(); });
    $('intakePrev').addEventListener('click',()=>{if(state.intakePage>1){state.intakePage--;renderIntakeTable(getFilteredIntake());}}); $('intakeNext').addEventListener('click',()=>{state.intakePage++;renderIntakeTable(getFilteredIntake());});

    let ct; $('callSearch').addEventListener('input',()=>{clearTimeout(ct);ct=setTimeout(()=>{state.callPage=1;renderCalls();},220)});
    ['callStartDate','callEndDate','callStaffFilter','callDirectionFilter','callResponseFilter'].forEach(id=>$(id).addEventListener('change',()=>{state.callPage=1;renderCalls();}));
    $('callClear').addEventListener('click',()=>{ $('callSearch').value=''; $('callStartDate').value=''; $('callEndDate').value=''; ['callStaffFilter','callDirectionFilter','callResponseFilter'].forEach(id=>$(id).value='All'); state.callPage=1; renderCalls(); });
    $('callPrev').addEventListener('click',()=>{if(state.callPage>1){state.callPage--;renderCallTable(getFilteredCalls());}}); $('callNext').addEventListener('click',()=>{state.callPage++;renderCallTable(getFilteredCalls());});

    $('modalClose').addEventListener('click',closeModal); $('detailModal').addEventListener('click',e=>{if(e.target===$('detailModal'))closeModal();}); document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
  }

  function switchPage(page){
    state.page=page;
    document.querySelectorAll('.page-button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));
    $('patientsPage').classList.toggle('hidden',page!=='patients'); $('intakePage').classList.toggle('hidden',page!=='intake'); $('callsPage').classList.toggle('hidden',page!=='calls');
    if(page==='patients')renderPatients(); else if(page==='intake')renderIntake(); else renderCalls();
  }

  function getFilteredPatients(){ const q=lower($('patientSearch').value), a=$('patientAcoFilter').value,n=$('patientNurseFilter').value,p=$('patientPriorityFilter').value,s=$('patientStatusFilter').value; return DATA.patients.filter(x=>{const hay=[x.firstName,x.lastName,x.practice,x.provider,x.uniqueId,x.beneficiaryId].map(lower).join(' ');return (!q||hay.includes(q))&&(a==='All'||x.aco===a)&&(n==='All'||(n==='Unassigned'?!str(x.nurse):x.nurse===n))&&(p==='All'||(p==='No Priority'?!str(x.priority):x.priority===p))&&(s==='All'||(s==='Not Started'?!str(x.status):x.status===s));}); }
  function renderPatients(){ const rows=getFilteredPatients(); renderPatientKpis(rows); renderPatientCharts(rows); renderPatientTable(rows); }
  function renderPatientKpis(rows){ const assigned=rows.filter(x=>str(x.nurse)).length, started=rows.filter(hasOutreach).length, reached=rows.filter(hasReached).length, active=rows.filter(x=>lower(x.status)==='enrolled, active care management').length, overdue=rows.filter(x=>lower(x.followUpOverdue)==='overdue').length, high=rows.filter(x=>lower(x.priority)==='high').length; $('patientKpis').innerHTML=[kpi('👥','Total Patients',num(rows.length),'Current filtered population','#7da9d8'),kpi('🩺','Assigned to Nurse',num(assigned),pct(assigned,rows.length)+' of patients','#6f9fd1'),kpi('☎','Outreach Started',num(started),pct(started,rows.length)+' of patients','#e5ad6f'),kpi('✓','Reached at Least Once',num(reached),pct(reached,started)+' of outreach','#7fb497'),kpi('⏱','Follow-Up Overdue',num(overdue),'Requires follow-up','#e5ad6f'),kpi('!','High Priority',num(high),'High-priority patients','#d98a8a')].join(''); }
  function renderPatientCharts(rows){
    const worked=rows.filter(x=>str(x.status)); const sc=sortedEntries(countBy(worked,x=>x.status)); makeDoughnut('patientStatus','patientStatusChart',sc.map(x=>x[0]),sc.map(x=>x[1]));
    const nc=sortedEntries(countBy(rows.filter(x=>str(x.nurse)),x=>x.nurse)); makeChart('patientNurse','patientNurseChart','bar',nc.map(x=>x[0]),[{label:'Assigned Patients',data:nc.map(x=>x[1]),backgroundColor:'#6f9fd1',borderRadius:7}],{indexAxis:'y',plugins:{legend:{display:false}}});
    const acos=uniq(rows.map(x=>x.aco)); const assigned=acos.map(a=>rows.filter(x=>x.aco===a&&str(x.nurse)).length), started=acos.map(a=>rows.filter(x=>x.aco===a&&hasOutreach(x)).length); makeChart('patientAco','patientAcoChart','bar',acos,[{label:'Assigned',data:assigned,backgroundColor:'#7da9d8',borderRadius:6},{label:'Outreach Started',data:started,backgroundColor:'#6f9fd1',borderRadius:6}],{});
    const pc=sortedEntries(countBy(rows.filter(x=>str(x.priority)),x=>x.priority)); makeDoughnut('patientPriority','patientPriorityChart',pc.map(x=>x[0]),pc.map(x=>x[1]));
  }
  function renderPatientTable(rows){ const pages=Math.max(1,Math.ceil(rows.length/state.patientSize)); state.patientPage=Math.min(state.patientPage,pages); const start=(state.patientPage-1)*state.patientSize, slice=rows.slice(start,start+state.patientSize); $('patientCount').textContent=`Showing ${num(slice.length)} of ${num(rows.length)} patients`; $('patientPageInfo').textContent=`Page ${state.patientPage} of ${pages}`; $('patientPrev').disabled=state.patientPage<=1; $('patientNext').disabled=state.patientPage>=pages; $('patientTableBody').innerHTML=slice.length?slice.map((p,i)=>`<tr data-patient-index="${start+i}"><td><span class="cell-main">${esc(`${p.lastName||''}, ${p.firstName||''}`.replace(/^,\s*/,''))}</span><span class="cell-sub">${esc(p.uniqueId||'')}</span></td><td>${esc(p.aco)}</td><td class="truncate" title="${esc(p.practice)}">${esc(p.practice||'—')}</td><td class="truncate" title="${esc(p.provider)}">${esc(p.provider||'—')}</td><td>${p.nurse?badge(p.nurse,'blue'):badge('Unassigned','muted')}</td><td>${priorityBadge(p.priority)}</td><td class="truncate" title="${esc(p.trigger)}">${esc(p.trigger||'—')}</td><td>${statusBadge(p.status)}</td><td>${fmtDate(p.lastTouchDate)}</td><td>${lower(p.followUpOverdue)==='overdue'?badge('Overdue','red'):p.nextFollowUpDate?badge(fmtDate(p.nextFollowUpDate),'amber'):badge('—','muted')}</td></tr>`).join(''):`<tr><td colspan="10" class="empty-row">No patients match the selected filters.</td></tr>`; [...$('patientTableBody').querySelectorAll('tr[data-patient-index]')].forEach((tr,idx)=>tr.addEventListener('click',()=>openPatient(slice[idx]))); }

  function getFilteredIntake(){ const q=lower($('intakeSearch').value),a=$('intakeAcoFilter').value,c=$('intakeConsultantFilter').value,s=$('intakeStateFilter').value; return DATA.intakeForms.filter(x=>{const hay=[x.practice,x.tin,x.consultant].map(lower).join(' ');return(!q||hay.includes(q))&&(a==='All'||x.aco===a)&&(c==='All'||x.consultant===c)&&(s==='All'||x.formState===s);}); }
  function renderIntake(){const rows=getFilteredIntake();renderIntakeKpis(rows);renderIntakeCharts(rows);renderIntakeTable(rows);}
  function renderIntakeKpis(rows){const received=rows.filter(x=>lower(x.formReceived)==='yes').length,out=rows.length-received,acos=uniq(rows.map(x=>x.aco)).length,consultants=uniq(rows.map(x=>x.consultant)).length,recent=rows.filter(x=>x.dateReceived).sort((a,b)=>str(b.dateReceived).localeCompare(str(a.dateReceived))).slice(0,1)[0]?.dateReceived||''; $('intakeKpis').innerHTML=[kpi('🏢','Total Practices',num(rows.length),'Practices in intake tracker','#7da9d8'),kpi('✓','Forms Received',num(received),pct(received,rows.length)+' completion','#6f9fd1'),kpi('⌛','Outstanding',num(out),'Forms still outstanding','#e5ad6f'),kpi('%','Completion Rate',pct(received,rows.length),'Received / total','#e5ad6f'),kpi('◫','ACO Programs',num(acos),'Programs represented','#76b4bd'),kpi('👤','Consultants',num(consultants),recent?`Latest receipt ${fmtDate(recent)}`:'Assigned consultants','#c69aae')].join('');}
  function renderIntakeCharts(rows){ const acos=uniq(rows.map(x=>x.aco)); const rec=acos.map(a=>rows.filter(x=>x.aco===a&&lower(x.formReceived)==='yes').length),out=acos.map((a,i)=>rows.filter(x=>x.aco===a).length-rec[i]); makeChart('intakeAco','intakeAcoChart','bar',acos,[{label:'Received',data:rec,backgroundColor:'#6f9fd1',borderRadius:6},{label:'Outstanding',data:out,backgroundColor:'#e5ad6f',borderRadius:6}],{});
    const monthly={};rows.filter(x=>x.dateReceived).forEach(x=>{const m=x.dateReceived.slice(0,7);monthly[m]=(monthly[m]||0)+1;});const months=Object.keys(monthly).sort();makeChart('intakeTrend','intakeTrendChart','line',months, [{label:'Forms Received',data:months.map(m=>monthly[m]),borderColor:'#6f9fd1',backgroundColor:'rgba(111,159,209,.13)',fill:true,tension:.3,pointRadius:3}],{});
    const cc=sortedEntries(countBy(rows.filter(x=>str(x.consultant)),x=>x.consultant)).slice(0,12);makeChart('intakeConsultant','intakeConsultantChart','bar',cc.map(x=>x[0]),[{label:'Practices',data:cc.map(x=>x[1]),backgroundColor:'#e5ad6f',borderRadius:6}],{indexAxis:'y',plugins:{legend:{display:false}}});
    const rates=acos.map((a,i)=>{const total=rows.filter(x=>x.aco===a).length;return total?+(rec[i]/total*100).toFixed(1):0;});makeChart('intakeRate','intakeRateChart','bar',acos,[{label:'Completion %',data:rates,backgroundColor:'#7da9d8',borderRadius:6}],{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,max:100,ticks:{color:'#adb5bf',callback:v=>v+'%'},grid:{color:'rgba(160,178,196,.22)'}},x:{ticks:{color:'#718096'},grid:{color:'rgba(160,178,196,.22)'}}}}); }
  function renderIntakeTable(rows){ const pages=Math.max(1,Math.ceil(rows.length/state.intakeSize));state.intakePage=Math.min(state.intakePage,pages);const start=(state.intakePage-1)*state.intakeSize,slice=rows.slice(start,start+state.intakeSize);$('intakeCount').textContent=`Showing ${num(slice.length)} of ${num(rows.length)} practices`;$('intakePageInfo').textContent=`Page ${state.intakePage} of ${pages}`;$('intakePrev').disabled=state.intakePage<=1;$('intakeNext').disabled=state.intakePage>=pages;$('intakeTableBody').innerHTML=slice.length?slice.map((x,i)=>`<tr data-intake-index="${i}"><td>${esc(x.aco)}</td><td><span class="cell-main">${esc(x.practice)}</span></td><td>${esc(x.tin||'—')}</td><td>${esc(x.consultant||'—')}</td><td>${fmtDate(x.dateStarted)}</td><td>${formBadge(x.formState)}</td><td>${fmtDate(x.dateReceived)}</td><td>${esc(x.status||'—')}</td><td class="truncate" title="${esc(x.notes)}">${esc(x.notes||'—')}</td></tr>`).join(''):`<tr><td colspan="9" class="empty-row">No intake records match the selected filters.</td></tr>`; [...$('intakeTableBody').querySelectorAll('tr[data-intake-index]')].forEach((tr,i)=>tr.addEventListener('click',()=>openIntake(slice[i]))); }

  function getFilteredCalls(){ const q=lower($('callSearch').value),start=$('callStartDate').value,end=$('callEndDate').value,staff=$('callStaffFilter').value,dir=$('callDirectionFilter').value,resp=$('callResponseFilter').value; return DATA.calls.filter(x=>{const hay=[x.fromName,x.fromNumber,x.toName,x.toNumber,x.owner].map(lower).join(' ');return(!q||hay.includes(q))&&(!start||x.date>=start)&&(!end||x.date<=end)&&(staff==='All'||x.owner===staff)&&(dir==='All'||x.direction===dir)&&(resp==='All'||x.response===resp);}); }
  function renderCalls(){const rows=getFilteredCalls();renderCallKpis(rows);renderCallCharts(rows);renderCallTable(rows);}
  function renderCallKpis(rows){const outbound=rows.filter(x=>lower(x.direction)==='outbound').length,inbound=rows.filter(x=>lower(x.direction)==='inbound').length,connected=rows.filter(isConnected).length,totalSec=rows.reduce((s,x)=>s+Number(x.lengthSeconds||0),0),avg=rows.length?totalSec/rows.length:0;$('callKpis').innerHTML=[kpi('☎','Total Calls',num(rows.length),'Current filtered call volume','#7da9d8'),kpi('↗','Outbound',num(outbound),pct(outbound,rows.length)+' of calls','#e5ad6f'),kpi('↙','Inbound',num(inbound),pct(inbound,rows.length)+' of calls','#76b4bd'),kpi('✓','Connected / Answered',num(connected),pct(connected,rows.length)+' connection rate','#6f9fd1'),kpi('⏱','Talk Time',(totalSec/3600).toFixed(1)+' hrs','Total recorded duration','#e5ad6f'),kpi('◷','Average Call',fmtDuration(avg),'Average recorded duration','#c69aae')].join('');}
  function renderCallCharts(rows){const owners=sortedEntries(countBy(rows.filter(x=>x.owner&&x.owner!=='Unassigned'),x=>x.owner));makeChart('callStaff','callStaffChart','bar',owners.map(x=>x[0]),[{label:'Calls',data:owners.map(x=>x[1]),backgroundColor:'#6f9fd1',borderRadius:7}],{indexAxis:'y',plugins:{legend:{display:false}}}); const daily=countBy(rows.filter(x=>x.date),x=>x.date),dates=Object.keys(daily).sort();makeChart('callTrend','callTrendChart','line',dates,[{label:'Calls',data:dates.map(d=>daily[d]),borderColor:'#7da9d8',backgroundColor:'rgba(125,169,216,.14)',fill:true,tension:.25,pointRadius:2}],{});const rc=sortedEntries(countBy(rows,x=>x.response));makeDoughnut('callResponse','callResponseChart',rc.map(x=>x[0]),rc.map(x=>x[1]));const staff=owners.map(x=>x[0]),rates=staff.map(n=>{const sub=rows.filter(x=>x.owner===n);return sub.length?+(sub.filter(isConnected).length/sub.length*100).toFixed(1):0;});makeChart('callRate','callRateChart','bar',staff,[{label:'Connection %',data:rates,backgroundColor:'#e5ad6f',borderRadius:7}],{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,max:100,ticks:{color:'#adb5bf',callback:v=>v+'%'},grid:{color:'rgba(160,178,196,.22)'}},x:{ticks:{color:'#718096'},grid:{color:'rgba(160,178,196,.22)'}}}});}
  function renderCallTable(rows){const sorted=[...rows].sort((a,b)=>str(b.dateTime).localeCompare(str(a.dateTime)));const pages=Math.max(1,Math.ceil(sorted.length/state.callSize));state.callPage=Math.min(state.callPage,pages);const start=(state.callPage-1)*state.callSize,slice=sorted.slice(start,start+state.callSize);$('callCount').textContent=`Showing ${num(slice.length)} of ${num(rows.length)} calls`;$('callPageInfo').textContent=`Page ${state.callPage} of ${pages}`;$('callPrev').disabled=state.callPage<=1;$('callNext').disabled=state.callPage>=pages;$('callTableBody').innerHTML=slice.length?slice.map((x,i)=>`<tr data-call-index="${i}"><td>${fmtDateTime(x.dateTime)}</td><td>${badge(x.owner||'Unassigned','blue')}</td><td><span class="cell-main">${esc(x.fromName||'—')}</span><span class="cell-sub">${esc(x.fromNumber||'')}</span></td><td><span class="cell-main">${esc(x.toName||'—')}</span><span class="cell-sub">${esc(x.toNumber||'')}</span></td><td>${lower(x.direction)==='outbound'?badge(x.direction,'purple'):badge(x.direction,'cyan')}</td><td>${fmtDuration(x.lengthSeconds)}</td><td>${responseBadge(x.response)}</td><td>${esc(x.result||'—')}</td></tr>`).join(''):`<tr><td colspan="8" class="empty-row">No calls match the selected filters.</td></tr>`; [...$('callTableBody').querySelectorAll('tr[data-call-index]')].forEach((tr,i)=>tr.addEventListener('click',()=>openCall(slice[i])));}

  function detail(label,value,full=false){return `<div class="detail-item${full?' full':''}"><span class="detail-label">${esc(label)}</span><div class="detail-value">${value??'—'}</div></div>`;}
  function openModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=`<div class="detail-grid">${html}</div>`;$('detailModal').classList.add('open');$('detailModal').setAttribute('aria-hidden','false');}
  function closeModal(){$('detailModal').classList.remove('open');$('detailModal').setAttribute('aria-hidden','true');}
  function openPatient(p){openModal(`${p.firstName||''} ${p.lastName||''}`.trim()||'Patient Detail',[
    detail('ACO',esc(p.aco)),detail('Unique ID',esc(p.uniqueId||'—')),detail('Beneficiary ID',esc(p.beneficiaryId||'—')),detail('Date of Birth',fmtDate(p.dob)),detail('Practice',esc(p.practice||'—')),detail('Provider',esc(p.provider||'—')),detail('Assigned Nurse',esc(p.nurse||'Unassigned')),detail('Priority',priorityBadge(p.priority)),detail('Primary Outreach Trigger',esc(p.trigger||'—')),detail('Outreach Status',statusBadge(p.status)),detail('Attempt 1',`${fmtDate(p.attempt1Date)} — ${esc(p.attempt1Outcome||'—')}`),detail('Attempt 2',`${fmtDate(p.attempt2Date)} — ${esc(p.attempt2Outcome||'—')}`),detail('Attempt 3',`${fmtDate(p.attempt3Date)} — ${esc(p.attempt3Outcome||'—')}`),detail('Last Touch',fmtDate(p.lastTouchDate)),detail('Assessment Completed',esc(p.assessmentCompleted||'—')),detail('Next Follow-Up',fmtDate(p.nextFollowUpDate)),detail('Follow-Up Overdue',esc(p.followUpOverdue||'—')),detail('Escalation',esc(p.escalationStatus||'—')),detail('Closure Reason',esc(p.closureReason||'—'),true),detail('Tracker Notes',esc(p.notes||'—'),true)
  ].join(''));}
  function openIntake(x){openModal(x.practice||'Intake Detail',[detail('ACO',esc(x.aco)),detail('TIN',esc(x.tin||'—')),detail('Consultant',esc(x.consultant||'—')),detail('Date Started',fmtDate(x.dateStarted)),detail('Form Status',formBadge(x.formState)),detail('Date Received',fmtDate(x.dateReceived)),detail('Source Status',esc(x.status||'—')),detail('Notes',esc(x.notes||'—'),true)].join(''));}
  function openCall(x){openModal(`${x.direction||'Call'} — ${fmtDateTime(x.dateTime)}`,[detail('Staff',esc(x.owner||'Unassigned')),detail('Duration',fmtDuration(x.lengthSeconds)),detail('From',`${esc(x.fromName||'—')}<br>${esc(x.fromNumber||'')}`),detail('To',`${esc(x.toName||'—')}<br>${esc(x.toNumber||'')}`),detail('Call Type',esc(x.callType||'—')),detail('Response',responseBadge(x.response)),detail('Result',esc(x.result||'—')),detail('Direction',esc(x.direction||'—'))].join(''));}

  window.addEventListener('load',init);
})();
